// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

var q1Input = Fs.readFileSync("src/aoc2020day3/Q_1.input.txt", "utf8");

var q2Input = Fs.readFileSync("src/aoc2020day3/Q_2.input.txt", "utf8");

console.log(q1Input);

console.log(q2Input);

exports.q1Input = q1Input;
exports.q2Input = q2Input;
/* q1Input Not a pure module */
