// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

var input1 = Fs.readFileSync("src/aoc2020day3/input1.txt", "utf8");

var input2 = Fs.readFileSync("src/aoc2020day3/input2.txt", "utf8");

console.log(input1);

console.log(input2);

exports.input1 = input1;
exports.input2 = input2;
/* input1 Not a pure module */
