// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var hello = "Hello";

var res = "ReScript";

function concat(a, b) {
  return a + b;
}

function greeting(param) {
  console.log(hello + " " + res);
}

greeting(undefined);

exports.hello = hello;
exports.res = res;
exports.concat = concat;
exports.greeting = greeting;
/*  Not a pure module */
