// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var a = "World";

function concat(a, b) {
  return a + b;
}

console.log("Hello" + a);

exports.a = a;
exports.concat = concat;
/*  Not a pure module */
